apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
  labels:
    app: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template: # how create each individual pod in the deployment
    metadata:
      labels: 
        app: tickets
    spec:
      containers:
        - name: tickets
          image: edgarolivar16/ticket_services:latest
          imagePullPolicy: IfNotPresent
          command: ["yarn", "tickets"]
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: EVENT_CLUSTER_ID
              value: 'ticketing'
            - name: EVENT_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: EVENT_URL
              value: 'http://nats-srv:4222'
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
---

apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      port: 3000
      targetPort: 3000
      protocol: TCP