name : tests-auth
on:
  pull_request:
    paths:
      - 'services/src/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services && npm install && npm run auth:test:ci
