name : tests-orders
on:
  pull_request:
    paths:
      - 'services/src/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services && npm install && npm run orders:test:ci
